[formatter.mdformat]
command = "uv"
includes = ["*.md", "**/*.md"]
options = [
  "run",
  "mdformat",
  "--wrap",
  "80",
  "--end-of-line",
  "lf",
  "--extensions",
  "frontmatter",
  "--extensions",
  "gfm",
  "--compact-tables",
]
